src/Entity/User.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity("tag_rfid")
 */
class User {
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $tag_rfid;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Transaction", mappedBy="user")
     */
    private $transactions;

    public function __construct() {
        $this->transactions = new ArrayCollection();
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getFirstname(): ?string {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self {
        $this->lastname = $lastname;

        return $this;
    }

    public function getTagRfid(): ?string {
        return $this->tag_rfid;
    }

    public function setTagRfid(string $tag_rfid): self {
        $this->tag_rfid = $tag_rfid;

        return $this;
    }

    public function getStatus(): ?string {
        return $this->status;
    }

    public function setStatus(string $status): self {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Transaction[]
     */
    public function getTransactions(): Collection {
        return $this->transactions;
    }

    public function addTransaction(Transaction $transaction): self {
        if (!$this->transactions->contains($transaction)) {
            $this->transactions[] = $transaction;
            $transaction->setUser($this);
        }

        return $this;
    }

    public function removeTransaction(Transaction $transaction): self {
        if ($this->transactions->contains($transaction)) {
            $this->transactions->removeElement($transaction);
            // set the owning side to null (unless already changed)
            if ($transaction->getUser() === $this) {
                $transaction->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function updateTimestamps(): void {
        $createdAt = new DateTime('now');
        if ($this->getCreatedAt() === null)
            $this->setCreatedAt($createdAt);
    }

    public function __toString() {
        return (string)$this->getId();
    }
}

src/Controller/UsersController.php
<?php


namespace App\Controller;


use App\Repository\TransactionRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UsersController extends AbstractController {

    /**
     * @Route("/users/new", name="user_list_new")
     */
    public function newUsers(UserRepository $userRepository) {
        $users = $userRepository->findAllNew();
        return $this->render('users/newUserList.html.twig', ['users' => $users]);
    }

    /**
     * @Route("/user/{userID}/edit", name="user_edit", methods={"GET"})
     * @param $userID
     * @param UserRepository $userRepository
     * @return Response
     */
    public function editUser($userID, UserRepository $userRepository, Request $request) {
        $user = $userRepository->find($userID);
        return $this->render('users/editUser.html.twig', ['user' => $user]);
    }

    /**
     * @Route("/user/{userID}/edit", name="user_edit_post", methods={"POST"})
     * @param $userID
     * @param Request $request
     * @param UserRepository $userRepository
     * @return Response
     */
    public function editUserPost($userID, Request $request, UserRepository $userRepository) {
        $req = $request->request;
        if(($firstname = $req->get('firstname')) && ($lastname = $req->get('lastname'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $user = $userRepository->find($userID);
            if($user) {
                $user->setFirstname($firstname);
                $user->setLastname($lastname);
                if ($user->getStatus() === 'NEW') {
                    $user->setStatus('ACTIVE');
                }
                $entityManager->flush();
            }
        }
        $this->addFlash('success', 'Utilisateur modifié avec succès');
        return $this->redirectToRoute('user_info', ['userID' => $userID]);
    }

    /**
     * @Route("/user/{userID}", name="user_info")
     * @param $userID
     * @param UserRepository $userRepository
     * @param TransactionRepository $transactionRepository
     * @return Response
     */
    public function info($userID, UserRepository $userRepository, TransactionRepository $transactionRepository) {
        $user = $userRepository->find($userID);
        $transactions = $transactionRepository->findBy(['user' => $user], ['date' => 'DESC']);
        $balance = 0;
        foreach ($user->getTransactions() as $transaction) {
            if($transaction->getStatus() != 'CANCELED') {
                $balance += $transaction->getAmount();
            }
        }
        return $this->render('users/infoUser.html.twig', ['user' => $user, 'transactions' => $transactions, 'balance' => $balance]);
    }

    /**
     * @Route("/users", name="user_list")
     * @param UserRepository $userRepository
     * @return Response
     */
    public function listUsers(Request $request, UserRepository $userRepository) {
        if($query = $request->query->get('q')) {
            $users = $userRepository->searchByLastnameOrFirstname($query);
            return $this->render('users/listUser.html.twig', ['users' => $users, 'query' => $query]);
        } else {
            $users = $userRepository->findAllCustom();
            return $this->render('users/listUser.html.twig', ['users' => $users]);
        }
    }

    /**
     * @Route("/user/{userID}/lock", name="user_lock")
     */
    public function lock($userID, UserRepository $userRepository) {
        $entityManager = $this->getDoctrine()->getManager();
        $user = $userRepository->find($userID);
        $user->setStatus('BLOCKED');
        $entityManager->flush();
        $this->addFlash('success', "<i class='fa fa-user-lock'></i> {$user->getFirstname()} {$user->getLastname()} est maintenant bloqué");
        return $this->redirectToRoute('user_info', ['userID' => $userID]);
    }

    /**
     * @Route("/user/{userID}/unlock", name="user_unlock")
     */
    public function unlock($userID, UserRepository $userRepository) {
        $entityManager = $this->getDoctrine()->getManager();
        $user = $userRepository->find($userID);
        $user->setStatus('ACTIVE');
        $entityManager->flush();
        $this->addFlash('success', "<i class='fa fa-unlock'></i> {$user->getFirstname()} {$user->getLastname()} est maintenant débloqué");
        return $this->redirectToRoute('user_info', ['userID' => $userID]);
    }

    /**
     * @Route("/user/{userID}/delete", name="user_delete")
     */
    public function delete($userID, UserRepository $userRepository) {
        /*$entityManager = $this->getDoctrine()->getManager();
        $user = $userRepository->find($userID);
        $entityManager->remove($user);
        $entityManager->flush();*/
        $this->addFlash('danger', 'Les utilisateurs ne peuvent pas être supprimés pour l\'instant');
        return $this->redirectToRoute('user_list');
    }

}

templates/users/editUser.html.twig
{% extends "layout.html.twig" %}

{% block main %}
    <h1>
        <i class="fa fa-user-edit"></i>
        {% if user.firstname is not empty and user.lastname is not empty %}
            {{ user.firstname }} {{ user.lastname }}
        {% else %}
            RFID {{ user.tagRfid }}
        {% endif %}
    </h1>
    <hr>
    {% if user.status == 'BLOCKED' %}
        <div class="alert alert-warning" role="alert">
            <strong><i class="fa fa-exclamation-triangle"></i> Ce compte est actuellement bloqué !</strong>
        </div>
    {% endif %}
    <form method="post" class="needs-validation" novalidate>
        <div class="form-row">
            <div class="col-sm-6 mb-3">
                <label for="firstname">Prénom</label>
                <input type="text" class="form-control" id="firstname" name="firstname" value="{{ user.firstname }}"
                       required>
                <div class="invalid-feedback">
                    Le prénom est requis.
                </div>
            </div>
            <div class="col-sm-6 mb-3">
                <label for="lastname">Nom</label>
                <input type="text" class="form-control" id="lastname" name="lastname" value="{{ user.lastname }}"
                       required>
                <div class="invalid-feedback">
                    Le nom est requis.
                </div>
            </div>
        </div>
        <button class="btn btn-primary" type="submit"><i class="fa fa-edit"></i> Modifier</button>
        <a href="{{ referer }}" class="btn btn-outline-secondary">Annuler</a>
    </form>

    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function () {
            'use strict';
            window.addEventListener('load', function () {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('needs-validation');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>
{% endblock %}

templates/users/infoUser.html.twig
{% extends "layout.html.twig" %}

{% block main %}
    <h1>
        <i class="fa fa-user"></i>
        {% if user.firstname is not empty and user.lastname is not empty %}
            {{ user.firstname }} {{ user.lastname }}
        {% else %}
            RFID {{ user.tagRfid }}
        {% endif %}
    </h1>
    <hr>
    {% if user.status == 'BLOCKED' %}
        <div class="alert alert-warning" role="alert">
            <strong><i class="fa fa-exclamation-triangle"></i> Ce compte est actuellement bloqué !</strong>
        </div>
    {% endif %}
    <a href="{{ path('user_edit', {userID: user.id}) }}" class="btn btn-primary"><i class="fa fa-edit"></i> Éditer</a>
    <a href="{{ path('user_delete', {userID: user.id}) }}" class="btn btn-outline-danger"
       onclick="return confirm('Êtes-vous sûr de vouloir supprimer cet utilisateur ? Cette action est irréverible.')"><i
                class="fa fa-trash"></i> Supprimer</a>
    <dl class="row mt-4">
        {% if user.lastname %}
            <dt class="col-4">Nom</dt>
            <dd class="col-8">{{ user.lastname }}</dd>
        {% endif %}

        {% if user.firstname %}
            <dt class="col-4">Prénom</dt>
            <dd class="col-8">{{ user.firstname }}</dd>
        {% endif %}

        <dt class="col-4">Tag RFID <i class="fa fa-credit-card"></i></dt>
        <dd class="col-8">{{ user.tagRfid }}</dd>

        <dt class="col-4">Statut du compte</dt>
        {% if user.status == 'ACTIVE' %}
            <dd class="col-8">
                <i class="fa fa-check text-success"></i> Actif
                <a href="{{ path('user_lock', {userID: user.id}) }}" class="btn btn-outline-danger ml-3"><i
                            class="fa fa-minus-circle"></i> Bloquer</a>
            </dd>
        {% elseif user.status == 'NEW' %}
            <dd class="col-8"><i class="fa fa-plus-circle text-primary"></i> Nouveau</dd>
        {% elseif user.status == 'BLOCKED' %}
            <dd class="col-8">
                <i class="fa fa-minus-circle text-danger"></i> Bloqué
                <a href="{{ path('user_unlock', {userID: user.id}) }}" class="btn btn-outline-success ml-3"><i
                            class="fa fa-unlock"></i> Débloquer</a>
            </dd>
        {% else %}
            <dd class="col-8"><i class="fa fa-question-circle"></i> Statut inconnu</dd>
        {% endif %}

        <dt class="col-4">Solde du compte</dt>
        <dd class="col-8 {{ balance < 0 ? 'text-danger' : balance > 0 ? 'text-success' }}">{{ balance }} CHF</dd>

        <dt class="col-4">Compte créé le</dt>
        <dd class="col-8">{{ user.createdAt|date('d.m.Y à H:i') }}</dd>
    </dl>

    <h2><i class="fa fa-tags"></i> Transactions <a class="text-info" href="#"><i class="fa fa-plus"></i></a></h2>
    <hr>
    <form method="get">
        <div class="form-group">
            <label for="search" class="sr-only"></label>
            <div class="input-group mb-3">
                <input type="search" class="form-control" placeholder="Rechercher" value="{{ query|default }}" name="q"
                       id="search" aria-describedby="search">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit"><i class="fa fa-search"></i></button>
                </div>
                {% if query is defined %}
                    <div class="input-group-append">
                        <a class="btn btn-outline-danger" href="{{ path('user_info', {userID: user.id}) }}"><i class="fa fa-filter"></i>
                            Clear</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </form>
    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th>No</th>
                <th>Montant</th>
                <th>Date</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for transaction in transactions %}
                <tr class="{{ transaction.status == 'CANCELED' ? 'striked table-warning' }}">
                    <td><a href="{{ path('transaction_info', {id: transaction.id}) }}">{{ transaction.id }}</a></td>
                    <td>{{ transaction.amount }} CHF</td>
                    <td>{{ transaction.date|date('d.m.Y H:i') }}</td>
                    <td>
                        <a href="{{ path('transaction_edit', {id: transaction.id}) }}" class="btn btn-sm btn-outline-info d-none d-sm-inline"><i
                                    class="fa fa-pencil-alt"></i></a>
                        {% if transaction.status == 'CANCELED' %}
                            <a href="{{ path('transaction_maintain', {id: transaction.id}) }}" class="btn btn-sm btn-outline-success d-none d-md-inline"><i
                                        class="fa fa-check"></i></a>
                        {% else %}
                            <a href="{{ path('transaction_cancel', {id: transaction.id}) }}" class="btn btn-sm btn-outline-danger d-none d-md-inline"><i
                                        class="fa fa-minus-circle"></i></a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if user.transactions is empty %}
            <p class="text-muted text-center">Aucune transaction pour le moment</p>
        {% endif %}
    </div>

{% endblock %}

templates/users/listUser.html.twig
{% extends "layout.html.twig" %}

{% block main %}
    <h1><i class="fa fa-users"></i> Utilisateurs</h1>
    <hr>
    <form method="get">
        <div class="form-group">
            <label for="search" class="sr-only"></label>
            <div class="input-group mb-3">
                <input type="search" class="form-control" placeholder="Rechercher" value="{{ query|default }}" name="q"
                       id="search" aria-describedby="search">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit"><i class="fa fa-search"></i></button>
                </div>
                {% if query is defined %}
                    <div class="input-group-append">
                        <a class="btn btn-outline-danger" href="{{ path('user_list') }}"><i class="fa fa-filter"></i>
                            Clear</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </form>
    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th>Nom</th>
                <th>Statut</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td><a href="{{ path('user_info', {userID: user.id}) }}">{{ user.firstname }} {{ user.lastname }}</a></td>
                    {% if user.status == 'ACTIVE' %}
                        <td><i class="fa fa-check text-success"></i></td>
                    {% elseif user.status == 'NEW' %}
                        <td><i class="fa fa-plus-circle text-primary"></i></td>
                    {% elseif user.status == 'BLOCKED' %}
                        <td><i class="fa fa-minus-circle text-danger"></i></td>
                    {% else %}
                        <td><i class="fa fa-question-circle"></i></td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/users/newUserList.html.twig
{% extends "layout.html.twig" %}

{% block main %}
    <h1><i class="fa fa-users"></i> Utilisateurs</h1>
    <hr>
    <form method="get">
        <div class="form-group">
            <label for="search" class="sr-only"></label>
            <div class="input-group mb-3">
                <input type="search" class="form-control" placeholder="Rechercher" value="{{ query|default }}" name="q"
                       id="search" aria-describedby="search">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit"><i class="fa fa-search"></i></button>
                </div>
                {% if query is defined %}
                    <div class="input-group-append">
                        <a class="btn btn-outline-danger" href="{{ path('user_list') }}"><i class="fa fa-filter"></i>
                            Clear</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </form>
    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th>RFID</th>
                <th>Date d'ajout</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.tagRfid }}</td>
                    <td>{{ user.createdAt|date('d.m.Y H:i') }}</td>
                    <td>
                        <a href="{{ path('user_edit', {userID: user.id}) }}" class="btn btn-success"><i class="fa fa-user-plus"></i></a>
                        <a href="{{ path('user_delete', {userID: user.id}) }}" class="btn btn-outline-danger" onclick="return confirm('Êtes-vous sûr de vouloir supprimer cette entrée ? Cette action est irréversible.')"><i class="fa fa-user-minus"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}