src/Entity/Transaction.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TransactionRepository")
 */
class Transaction
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     */
    private $num_terminal;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="transactions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin", inversedBy="transactions", )
     * @ORM\JoinColumn(name="admin_id", referencedColumnName="user_id", nullable=false)
     */
    private $admin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $status;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getNumTerminal(): ?int
    {
        return $this->num_terminal;
    }

    public function setNumTerminal(int $num_terminal): self
    {
        $this->num_terminal = $num_terminal;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getAdmin(): ?Admin
    {
        return $this->admin;
    }

    public function setAdmin(?Admin $admin): self
    {
        $this->admin = $admin;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Controller/TransactionsController.php
<?php


namespace App\Controller;


use App\Repository\TransactionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TransactionsController extends AbstractController {

    /**
     * @Route("/history", name="history")
     */
    public function history(Request $request, TransactionRepository $transactionRepository) {
        if ($query = $request->query->get('q')) {
            //$transactions = $transactionRepository->searchByLastnameOrFirstname($query);
            return $this->render('transactions/history.html.twig', ['transactions' => [], 'query' => $query]);
        } else {
            $transactions = $transactionRepository->findAllSorted();
            return $this->render('transactions/history.html.twig', ['transactions' => $transactions]);
        }
    }

    /**
     * @Route("/transaction/{id}", name="transaction_info")
     * @param $id
     * @param TransactionRepository $repo
     * @return Response
     */
    public function info($id, TransactionRepository $repo) {
        $transaction = $repo->find($id);
        if ($transaction) {
            return $this->render('transactions/info.html.twig', ['transaction' => $transaction]);
        } else {
            return $this->render('404.html.twig');
        }
    }

    /**
     * @Route("/transaction/{id}/cancel", name="transaction_cancel")
     * @param $id
     * @param Request $request
     * @param TransactionRepository $repo
     * @return Response
     */
    public function cancel($id, Request $request, TransactionRepository $repo) {
        $manager = $this->getDoctrine()->getManager();
        $transaction = $repo->find($id);
        if ($transaction) {
            $transaction->setStatus('CANCELED');
            $manager->flush();
            $this->addFlash('success', "<i class='fa fa-minus-circle text-danger'></i> La transaction {$id} est annulée.");
            $referer = $request->headers->get('referer');
            if ($referer) {
                return $this->redirect($referer);
            } else {
                return $this->redirectToRoute('transaction_info', ['id' => $id]);
            }
        } else {
            return $this->render('404.html.twig');
        }
    }

    /**
     * @Route("/transaction/{id}/maintain", name="transaction_maintain")
     * @param $id
     * @param Request $request
     * @param TransactionRepository $repo
     * @return Response
     */
    public function maintain($id, Request $request, TransactionRepository $repo) {
        $manager = $this->getDoctrine()->getManager();
        $transaction = $repo->find($id);
        if ($transaction) {
            $transaction->setStatus(null);
            $manager->flush();
            $this->addFlash('success', "<i class='fa fa-check'></i> La transaction {$id} est maintenue.");
            $referer = $request->headers->get('referer');
            if ($referer) {
                return $this->redirect($referer);
            } else {
                return $this->redirectToRoute('transaction_info', ['id' => $id]);
            }
        } else {
            return $this->render('404.html.twig');
        }
    }

    /**
     * @Route("/transaction/{id}/edit", name="transaction_edit", methods={"GET"})
     * @param $id
     * @param TransactionRepository $repo
     * @return Response
     */
    public function edit($id, TransactionRepository $repo) {
        $transaction = $repo->find($id);
        if ($transaction) {
            return $this->render('transactions/edit.html.twig', ['transaction' => $transaction]);
        } else {
            return $this->render('404.html.twig');
        }
    }

    /**
     * @Route("/transaction/{id}/edit", name="transaction_edit_post", methods={"POST"})
     * @param $id
     * @param Request $request
     * @param TransactionRepository $repo
     * @return Response
     */
    public function editPost($id, Request $request, TransactionRepository $repo) {
        $manager = $this->getDoctrine()->getManager();
        $transaction = $repo->find($id);
        if ($transaction) {
            if ($amount = $request->request->get('amount')) {
                if(is_numeric($amount)) {
                    $transaction->setAmount($amount);
                    $manager->flush();
                    $this->addFlash('success', '<i class=\'fa fa-check\'></i> La transaction a bien été mise à jour.');
                    return $this->redirectToRoute('transaction_info', ['id' => $id]);
                } else {
                    $this->addFlash('danger', 'Le montant doit être un nombre.');
                    return $this->redirectToRoute('transaction_edit', ['id' => $id]);
                }
            }
        }
        return $this->render('404.html.twig');
    }

}

templates/transactions/edit.html.twig
{% extends 'layout.html.twig' %}

{% block main %}
    <h1>
        <i class="fa fa-edit"></i>
        Transaction #{{ transaction.id }}
    </h1>
    <hr>
    {% if transaction.status == 'CANCELED' %}
        <div class="alert alert-warning" role="alert">
            <strong><i class="fa fa-exclamation-triangle"></i> Cette transaction est annulée.</strong> Elle n'est
            pas prise en compte dans les calculs des soldes mais reste présente dans la base de données.
        </div>
    {% endif %}
    <form method="post" class="needs-validation" novalidate>
        <div class="form-group row">
            <label class="col-3 col-form-label" for="user">Client</label>
            <div class="col-9">
                <input type="text" class="form-control" id="user"
                       value="{{ transaction.user.firstname }} {{ transaction.user.lastname }}" readonly disabled>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-3 col-form-label" for="amount">Montant</label>
            <div class="col-9">
                <div class="input-group mb-3">
                    <input type="text" class="form-control" placeholder="Montant de la transaction" name="amount"
                           id="amount"
                           value="{{ transaction.amount }}" aria-label="Montant de la transaction"
                           aria-describedby="basic-addon2" required>
                    <div class="input-group-append">
                        <span class="input-group-text" id="basic-addon2">CHF</span>
                    </div>
                    <div class="invalid-feedback">
                        Le montant est requis.
                    </div>
                </div>
            </div>
        </div>
        <button class="btn btn-primary" type="submit"><i class="fa fa-edit"></i> Modifier</button>
        <a href="{{ referer }}" class="btn btn-outline-secondary">Annuler</a>
    </form>

    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function () {
            'use strict';
            window.addEventListener('load', function () {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('needs-validation');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>
{% endblock %}

templates/transactions/history.html.twig
{% extends "layout.html.twig" %}

{% block main %}
    <h1><i class="fa fa-tags"></i> Transactions</h1>
    <hr>
    <form method="get">
        <div class="form-group">
            <label for="search" class="sr-only"></label>
            <div class="input-group mb-3">
                <input type="search" class="form-control" placeholder="Rechercher" value="{{ query|default }}" name="q"
                       id="search" aria-describedby="search">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit"><i class="fa fa-search"></i></button>
                </div>
                {% if query is defined %}
                    <div class="input-group-append">
                        <a class="btn btn-outline-danger" href="{{ path('history') }}"><i class="fa fa-filter"></i>
                            Clear</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </form>
    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th class="d-none d-md-table-cell">ID</th>
                <th>Utilisateur</th>
                <th>Montant</th>
                <th>Date</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for transaction in transactions %}
                <tr class="{{ transaction.status == 'CANCELED' ? 'striked table-warning' }}">
                    <td class="d-none d-md-table-cell"><a
                                href="{{ path('transaction_info', {id: transaction.id}) }}">{{ transaction.id }}</a>
                    </td>
                    <td>
                        <a href="{{ path('user_info', {userID: transaction.user_id}) }}">{{ transaction.firstname }} {{ transaction.lastname }}</a>
                    </td>
                    <td>{{ transaction.amount }}<span class="d-none d-sm-inline"> CHF</span></td>
                    <td>{{ transaction.date|date('d.m.y H:i') }}</td>
                    <td>
                        <a href="{{ path('transaction_info', {id: transaction.id}) }}"
                           class="btn btn-sm btn-outline-primary"><i class="fa fa-eye"></i></a>
                        <a href="{{ path('transaction_edit', {id: transaction.id}) }}" class="btn btn-sm btn-outline-info d-none d-sm-inline"><i
                                    class="fa fa-pencil-alt"></i></a>
                        {% if transaction.status == 'CANCELED' %}
                            <a href="{{ path('transaction_maintain', {id: transaction.id}) }}" class="btn btn-sm btn-outline-success d-none d-md-inline"><i
                                        class="fa fa-check"></i></a>
                        {% else %}
                            <a href="{{ path('transaction_cancel', {id: transaction.id}) }}" class="btn btn-sm btn-outline-danger d-none d-md-inline"><i
                                        class="fa fa-minus-circle"></i></a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if transactions is empty %}
            <p class="text-muted text-center">Pas de transaction pour le moment</p>
        {% endif %}
    </div>
{% endblock %}

templates/transactions/info.html.twig
{% extends 'layout.html.twig' %}

{% block main %}
    <h1>
        <i class="fa fa-tag"></i>
        Transaction #{{ transaction.id }}
    </h1>
    <hr>
    {% if transaction.status == 'CANCELED' %}
        <div class="alert alert-warning" role="alert">
            <strong><i class="fa fa-exclamation-triangle"></i> Cette transaction est annulée.</strong> Elle n'est
            pas prise en compte dans les calculs des soldes mais reste présente dans la base de données.
        </div>
    {% endif %}
    <a href="{{ path('transaction_edit', {id: transaction.id}) }}" class="btn btn-primary"><i class="fa fa-edit"></i> Éditer</a>
    {% if transaction.status == 'CANCELED' %}
        <a href="{{ path('transaction_maintain', {id: transaction.id}) }}" class="btn btn-outline-success">
            <i class="fa fa-check"></i>
            Maintenir la transaction
        </a>
    {% else %}
        <a href="{{ path('transaction_cancel', {id: transaction.id}) }}" class="btn btn-outline-danger">
            <i class="fa fa-minus-circle"></i>
            Annuler la transaction
        </a>
    {% endif %}
    <dl class="row mt-4">
        <dt class="col-4">Client</dt>
        <dd class="col-8"><a href="{{ path('user_info', {userID: transaction.user.id}) }}">{{ transaction.user.firstname }} {{ transaction.user.lastname }}</a></dd>

        <dt class="col-4">Admin</dt>
        <dd class="col-8">{{ transaction.admin.user.firstname }} {{ transaction.admin.user.lastname }}</dd>

        <dt class="col-4">Date</dt>
        <dd class="col-8">{{ transaction.date|date('d.m.Y H:i') }}</dd>

        <dt class="col-4">Montant</dt>
        <dd class="col-8">{{ transaction.amount }} CHF <i
                    class="fa fa-arrow-{{ transaction.amount > 0 ? 'up' : 'down' }} {{ transaction.amount > 0 ? 'text-success' : 'text-danger' }}"></i>
        </dd>

        <dt class="col-4">Numéro du terminal</dt>
        <dd class="col-8">N°{{ transaction.numTerminal }}</dd>
    </dl>
{% endblock %}